### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by duanpanjun** [WooKyoungHan/ABCD#2]
Hello, I'd like to ask why I'm encountering this error when training with my custom dataset.
For example:    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by WooKyoungHan** [comment]
Hi, Thanks for visiting my repo. 
I think there is a problem when setting your own path in the config(.yaml) file. Please set 
    args:
      root_path: ###_data_path
 the root path as str. 
Have a nice day :)

**Comment by duanpanjun** [comment]
> Hi, Thanks for visiting my repo.您好，感谢您访问我的存储库。 I think there is a problem when setting your own path in the config(.yaml) file. Please set 我认为在 config(.yaml) 文件中设置自己的路径时存在问题。请设定 args: 参数： root_path: ###_data_path 根路径：###_数据路径 the root path as str.根路径为 str。 Have a nice day :) 祝你今天过得愉快 ：）

OK, thank you for your response.
